### ISSUE TITLE
When two views overlap, there seems to be a bug

### ISSUE THREAD

**Issue by qiuyuliang** [ivanvorobei/SPPerspective#2]
My code is as follows![image](https://user-images.githubusercontent.com/9816199/121156073-f7916b80-c87a-11eb-8f11-323f1aaa00ba.png)
`let bottomView = UIView(frame: CGRect(x: 44, y: 44, width: 200, height: 200))
        bottomView.backgroundColor = .red
        view.addSubview(bottomView)

        // same position, has alpha 0.5
        let topView = UIView(frame: CGRect(x: 44, y: 44, width: 200, height: 200))
        topView.backgroundColor = UIColor(white: 1, alpha: 1)
        view.addSubview(topView)

        topView.applyPerspective(.iOS14WidgetAnimatable)`

![image](https://user-images.githubusercontent.com/9816199/121156073-f7916b80-c87a-11eb-8f11-323f1aaa00ba.png)

**Comment by ivanvorobei** [comment]
Are you apply to top view, why? Maybe need for parent-bottom?

**Comment by qiuyuliang** [comment]
Maybe the bottom view is just a decorative background

**Comment by ivanvorobei** [comment]
Can you create empty project for check it?

**Comment by qiuyuliang** [comment]
This can be replicated by adding the following code to any of the viewControllers

`import UIKit
import SPPerspective

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let bottomView = UIView(frame: CGRect(x: 0, y: 0, width: 400, height: 400))
        bottomView.backgroundColor = .red
        view.addSubview(bottomView)

        let topView = UIView(frame: CGRect(x: 44, y: 44, width: 200, height: 200))
        topView.backgroundColor = UIColor(white: 1, alpha: 1)
        view.addSubview(topView)

        topView.applyPerspective(.iOS14WidgetAnimatable)

    }
}`

**Comment by ivanvorobei** [comment]
Thanks! 
Fixed in `1.3.0` version.
